OnlineVote/config/routes.rb
Rails.application.routes.draw do
  resources :votes

  resources :staffers

  resources :bills

   root 'bills#index'

end

OnlineVote/app/models/bill.rb
class Bill < ActiveRecord::Base
  has_many :votes
  belongs_to :staffer
end

OnlineVote/app/models/staffer.rb
class Staffer < ActiveRecord::Base
  has_many :bills
end

OnlineVote/app/models/vote.rb
class Vote < ActiveRecord::Base
  belongs_to :bill
end

OnlineVote/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

OnlineVote/app/controllers/bills_controller.rb
class BillsController < ApplicationController
  before_action :set_bill, only: [:show, :edit, :update, :destroy]

  # GET /bills
  # GET /bills.json
  def index
    @bills = Bill.all
  end

  # GET /bills/1
  # GET /bills/1.json
  def show
  end

  # GET /bills/new
  def new
    @bill = Bill.new
  end

  # GET /bills/1/edit
  def edit
  end

  # POST /bills
  # POST /bills.json
  def create
    @bill = Bill.new(bill_params)

    respond_to do |format|
      if @bill.save
        format.html { redirect_to @bill, notice: 'Bill was successfully created.' }
        format.json { render :show, status: :created, location: @bill }
      else
        format.html { render :new }
        format.json { render json: @bill.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /bills/1
  # PATCH/PUT /bills/1.json
  def update
    respond_to do |format|
      if @bill.update(bill_params)
        format.html { redirect_to @bill, notice: 'Bill was successfully updated.' }
        format.json { render :show, status: :ok, location: @bill }
      else
        format.html { render :edit }
        format.json { render json: @bill.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bills/1
  # DELETE /bills/1.json
  def destroy
    @bill.destroy
    respond_to do |format|
      format.html { redirect_to bills_url, notice: 'Bill was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_bill
      @bill = Bill.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def bill_params
      params.require(:bill).permit(:staffer_id, :bill_text, :vote_id)
    end
end

OnlineVote/app/controllers/logins_controller.rb
class LoginsController < ApplicationController

  def create
  end

  def logout
  end

  private def make_session
  end 




end

OnlineVote/app/controllers/staffers_controller.rb
class StaffersController < ApplicationController
  before_action :set_staffer, only: [:show, :edit, :update, :destroy]

  # GET /staffers
  # GET /staffers.json
  def index
    @staffers = Staffer.all
  end

  # GET /staffers/1
  # GET /staffers/1.json
  def show
  end

  # GET /staffers/new
  def new
    @staffer = Staffer.new
  end

  # GET /staffers/1/edit
  def edit
  end

  # POST /staffers
  # POST /staffers.json
  def create
    @staffer = Staffer.new(staffer_params)

    respond_to do |format|
      if @staffer.save
        format.html { redirect_to @staffer, notice: 'Staffer was successfully created.' }
        format.json { render :show, status: :created, location: @staffer }
      else
        format.html { render :new }
        format.json { render json: @staffer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /staffers/1
  # PATCH/PUT /staffers/1.json
  def update
    respond_to do |format|
      if @staffer.update(staffer_params)
        format.html { redirect_to @staffer, notice: 'Staffer was successfully updated.' }
        format.json { render :show, status: :ok, location: @staffer }
      else
        format.html { render :edit }
        format.json { render json: @staffer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /staffers/1
  # DELETE /staffers/1.json
  def destroy
    @staffer.destroy
    respond_to do |format|
      format.html { redirect_to staffers_url, notice: 'Staffer was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_staffer
      @staffer = Staffer.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def staffer_params
      params.require(:staffer).permit(:name, :email, :password_digest)
    end
end

OnlineVote/app/controllers/votes_controller.rb
class VotesController < ApplicationController
  before_action :set_vote, only: [:show, :edit, :update, :destroy]

  # GET /votes
  # GET /votes.json
  def index
    @votes = Vote.all
  end

  # GET /votes/1
  # GET /votes/1.json
  def show
  end

  # GET /votes/new
  def new
    @vote = Vote.new
  end

  # GET /votes/1/edit
  def edit
  end

  # POST /votes
  # POST /votes.json
  def create
    @vote = Vote.new(vote_params)

    respond_to do |format|
      if @vote.save
        format.html { redirect_to @vote, notice: 'Vote was successfully created.' }
        format.json { render :show, status: :created, location: @vote }
      else
        format.html { render :new }
        format.json { render json: @vote.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /votes/1
  # PATCH/PUT /votes/1.json
  def update
    respond_to do |format|
      if @vote.update(vote_params)
        format.html { redirect_to @vote, notice: 'Vote was successfully updated.' }
        format.json { render :show, status: :ok, location: @vote }
      else
        format.html { render :edit }
        format.json { render json: @vote.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /votes/1
  # DELETE /votes/1.json
  def destroy
    @vote.destroy
    respond_to do |format|
      format.html { redirect_to votes_url, notice: 'Vote was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_vote
      @vote = Vote.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def vote_params
      params.require(:vote).permit(:vote_type, :bill_id, :voter_id)
    end
end

OnlineVote/app/helpers/application_helper.rb
module ApplicationHelper
end

OnlineVote/app/helpers/bills_helper.rb
module BillsHelper
end

OnlineVote/app/helpers/logins_helper.rb
module LoginsHelper
end

OnlineVote/app/helpers/staffers_helper.rb
module StaffersHelper
end

OnlineVote/app/helpers/votes_helper.rb
module VotesHelper
end

OnlineVote/app/views/bills/_form.html.erb
<%= form_for(@bill) do |f| %>
  <% if @bill.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@bill.errors.count, "error") %> prohibited this bill from being saved:</h2>

      <ul>
      <% @bill.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :staffer_id %><br>
    <%= f.number_field :staffer_id %>
  </div>
  <div class="field">
    <%= f.label :bill_text %><br>
    <%= f.text_area :bill_text %>
  </div>
  <div class="field">
    <%= f.label :vote_id %><br>
    <%= f.number_field :vote_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

OnlineVote/app/views/bills/edit.html.erb
<h1>Editing Bill</h1>

<%= render 'form' %>

<%= link_to 'Show', @bill %> |
<%= link_to 'Back', bills_path %>

OnlineVote/app/views/bills/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Bills</h1>

<table>
  <thead>
    <tr>
      <th>Staffer</th>
      <th>Bill text</th>
      <th>Vote</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @bills.each do |bill| %>
      <tr>
        <td><%= bill.staffer_id %></td>
        <td><%= bill.bill_text %></td>
        <td><%= bill.vote_id %></td>
        <td><%= link_to 'Show', bill %></td>
        <td><%= link_to 'Edit', edit_bill_path(bill) %></td>
        <td><%= link_to 'Destroy', bill, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Bill', new_bill_path %>

OnlineVote/app/views/bills/new.html.erb
<h1>New Bill</h1>

<%= render 'form' %>

<%= link_to 'Back', bills_path %>

OnlineVote/app/views/bills/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Staffer:</strong>
  <%= @bill.staffer_id %>
</p>

<p>
  <strong>Bill text:</strong>
  <%= @bill.bill_text %>
</p>

<p>
  <strong>Vote:</strong>
  <%= @bill.vote_id %>
</p>

<%= link_to 'Edit', edit_bill_path(@bill) %> |
<%= link_to 'Back', bills_path %>

OnlineVote/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>OnlineVote</title>
  <%= stylesheet_link_tag    'application', media: 'all'  %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

OnlineVote/app/views/logins/_form_staffer.html.erb
<%= form_tag :action => :staffer_login do %>
<%= text_field_tag :email, il, placeholder: "Email" %><br>
<%= password_field_tag :password, nil, placeholder: "Password" %><br>
<%= submit_tag 'Login' %><br>
<!-- <%#= link_to "Sign Up", new_staffer_path %> -->
<% end %>

OnlineVote/app/views/staffers/_form.html.erb
<%= form_for(@staffer) do |f| %>
  <% if @staffer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@staffer.errors.count, "error") %> prohibited this staffer from being saved:</h2>

      <ul>
      <% @staffer.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :password_digest %><br>
    <%= f.text_field :password_digest %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

OnlineVote/app/views/staffers/edit.html.erb
<h1>Editing Staffer</h1>

<%= render 'form' %>

<%= link_to 'Show', @staffer %> |
<%= link_to 'Back', staffers_path %>

OnlineVote/app/views/staffers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Staffers</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Password digest</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @staffers.each do |staffer| %>
      <tr>
        <td><%= staffer.name %></td>
        <td><%= staffer.email %></td>
        <td><%= staffer.password_digest %></td>
        <td><%= link_to 'Show', staffer %></td>
        <td><%= link_to 'Edit', edit_staffer_path(staffer) %></td>
        <td><%= link_to 'Destroy', staffer, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Staffer', new_staffer_path %>

OnlineVote/app/views/staffers/new.html.erb
<h1>New Staffer</h1>

<%= render 'form' %>

<%= link_to 'Back', staffers_path %>

OnlineVote/app/views/staffers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @staffer.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @staffer.email %>
</p>

<p>
  <strong>Password digest:</strong>
  <%= @staffer.password_digest %>
</p>

<%= link_to 'Edit', edit_staffer_path(@staffer) %> |
<%= link_to 'Back', staffers_path %>

OnlineVote/app/views/votes/_form.html.erb
<%= form_for(@vote) do |f| %>
  <% if @vote.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@vote.errors.count, "error") %> prohibited this vote from being saved:</h2>

      <ul>
      <% @vote.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :vote_type %><br>
    <%= f.check_box :vote_type %>
  </div>
  <div class="field">
    <%= f.label :bill_id %><br>
    <%= f.number_field :bill_id %>
  </div>
  <div class="field">
    <%= f.label :voter_id %><br>
    <%= f.number_field :voter_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

OnlineVote/app/views/votes/edit.html.erb
<h1>Editing Vote</h1>

<%= render 'form' %>

<%= link_to 'Show', @vote %> |
<%= link_to 'Back', votes_path %>

OnlineVote/app/views/votes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Votes</h1>

<table>
  <thead>
    <tr>
      <th>Vote type</th>
      <th>Bill</th>
      <th>Voter</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @votes.each do |vote| %>
      <tr>
        <td><%= vote.vote_type %></td>
        <td><%= vote.bill_id %></td>
        <td><%= vote.voter_id %></td>
        <td><%= link_to 'Show', vote %></td>
        <td><%= link_to 'Edit', edit_vote_path(vote) %></td>
        <td><%= link_to 'Destroy', vote, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Vote', new_vote_path %>

OnlineVote/app/views/votes/new.html.erb
<h1>New Vote</h1>

<%= render 'form' %>

<%= link_to 'Back', votes_path %>

OnlineVote/app/views/votes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Vote type:</strong>
  <%= @vote.vote_type %>
</p>

<p>
  <strong>Bill:</strong>
  <%= @vote.bill_id %>
</p>

<p>
  <strong>Voter:</strong>
  <%= @vote.voter_id %>
</p>

<%= link_to 'Edit', edit_vote_path(@vote) %> |
<%= link_to 'Back', votes_path %>